### ISSUE TITLE
Delete shortcut bad label

### ISSUE THREAD

**Issue by ZwickTheGreat** [mindjolt/starling-builder-editor#1]
There is some issue with delete keyboard shortcut.

![image](https://cloud.githubusercontent.com/assets/2446500/10869573/aaa86770-80b3-11e5-8c6c-49bf82ad2b87.png)

**Comment by ZwickTheGreat** [comment]
Oh, I see now in code, that default shortcurt is Ctrl+Backspace.

**Comment by ZwickTheGreat** [comment]
It would be awesome, if it would be just "Delete" or "Backspace" with no control.

**Comment by ghost** [comment]
The display label is a Windows only issue. Basically the Adobe Air api can't display non-letter short cut correctly. I have changed it to Delete or Backspace without shortcut as you suggested. https://github.com/mindjolt/starling-builder-editor/commit/df18224c72bea264ee4518ff8fae9e80d3f608b1
Thanks for the reporting!
