### ISSUE TITLE
Feature: Auto reload changes in images

### ISSUE THREAD

**Issue by HaimZik** [mindjolt/starling-builder-editor#16]
It is really a pain to edit texture files(from outside program).
Having it automatically update will drastically improve the experience using starling-builder.
Now you have to 
1)click on the reload button- solved by checking if the workspace file changed 
2)relaunch the all program- that can be avoided(not critical but would be nice)
3)manually reopen your scene file- open last scene on relaunch or not relaunching at all would solve it.

**Comment by ghost** [comment]
Thanks for the feedback. I will try to get this feature in the next version.

**Comment by ghost** [comment]
Implemented in v0.9.3 and v2.1.3.
