### ISSUE TITLE
Editable Quad size

### ISSUE THREAD

**Issue by MyMyGames** [mindjolt/starling-builder-editor#18]
Please, Add the ability  in  editor to specify the QUAD size , is now  sets  50x50 size by default ,now  resizing Quad is done by  Scale , it is not possible to use it in properly in inteface. We have to change the XML by hand.

**Comment by ghost** [comment]
Hi,

Could you tell me your use case where setting 50x50 size by default and changing the scale of the Quad won't work? I need to understand your issue to think of a better way to fix it.
Thanks.

**Comment by MyMyGames** [comment]
For example you need to make a simple progress bar.
I issue the size of 100% (scaleX: 1.0) and a width of 215 pixels.
By changing the size from 0% to 100% (scaleX: 0.0 .. 1.0) I with  no additional transformations get full progressbar, over which can put any design.
That is, I need to do Quad size 215x10 without scale (scale = 1). Now this is only possible by editing the file JSON by  hands.

This is one of several examples.
For mobile devices with complex multi-layer interface to optimize better to remove extra transformation.

**Comment by ghost** [comment]
Good point. I fixed it right away 44d7e8b1c26190ae76ca1aa21fe1513c34b52083

**Comment by MyMyGames** [comment]
It's doesn't work. when i'm changing size of Quad, scale should not change, SCALE still changes.

**Comment by yuhengh** [comment]
I'm afraid you can't do that without changing Starling. You can only set original size in the constructor. My recommendation is to adjust to the right size first, then create a new one with that as initial size.

**Comment by MyMyGames** [comment]
Сould it be done?
A new type of QUAD with an additional checkbox "scale_always_1". 
and when you're saving JSON, Editor resets SCALE to 1, and width and height will be saved to constructor

**Comment by ghost** [comment]
Hmm, I think this is too hacky to do. In your case if someone set scaleX = 0.5 and save it to then it's weird that scaleX is no longer 0.5. It's also not consistent as other display objects. I hope you understand!

**Comment by MyMyGames** [comment]
Just for understanding
In reality QUAD Doesn't need SCALE 0.5. at all. 
For QUAD scale should always be 1.

Can you give me an example when QUAD needs a SCALE?
Any scale except 1?

Sorry for persistence )

**Comment by ghost** [comment]
There may be not a case for Quad, but there may be a case for other display objects. I don't think it's a good idea to make Quad a special case, since it's also a display object.

**Comment by MyMyGames** [comment]
But TiledImage working without scale change. 
Why not do as well?

**Comment by ghost** [comment]
Because the mechanism is implemented inside TiledImage. The editor’s job is simply getting/setting properties, not changing how it works. You can modify Starling.display.Quad to not changing scale if you want, but not from the editor outside.
