### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by gadyosef** [mindjolt/starling-builder-editor#5]
This is an awesome tool, I really look forward to see it progressed by you guys or the community!

The problem I'm having is that after a while being active, the whole app becomes unresponsive (I also lost a layout because I had to kill the process).
I noticed the "Mem" field in the Starling stats little black window keep growing and growing, even if I didn't do anything after opening the app.
It also seem to grow more rapidly on mouse events (Clicks and movement).

Thank you for your amazing work!

**Comment by ghost** [comment]
Hi,

I am sorry for your lost!
You're right, the memory and performance issue has not been addressed yet.
I am currently working on an object pooling system which will significantly improve performance.
I will also fix the memory leak on the way and hopefully it will work out for you!
Thank you for the report, I really appreciate it and it is motivating me moving forward!

**Comment by ghost** [comment]
I recently made a big performance improvement in the v0.6.2 version. I have been doing some memory profiling as well, but I found nothing unusual.

> > The problem I'm having is that after a while being active, the whole app becomes unresponsive.

I never encountered this problem in my Macbook Pro Retina display.

> > I noticed the "Mem" field in the Starling stats little black window keep growing and growing, even if I didn't do anything after opening the app.

I can't seem to reproduce this one as well.

> > It also seem to grow more rapidly on mouse events (Clicks and movement).

This is happening to me, but after a while the gc gets in and the memory goes down again.

If you want to diagnose the issue more please send me an email to yhuang@sgn.com
